#ifndef VD_NAMES
#define VD_NAMES

#include <pgmspace.h>

// namedays, stored in program flash!
const char MONTH_1[] PROGMEM = {
    "Solvita Laimnesis Solvija\0"
    "Indulis Iva Ivis Ivo\0"
    "Ringolds Miervalda Miervaldis\0"
    "Ilva Spodra\0"
    "Sîmanis Zintis\0"
    "Arnita Spulga\0"
    "Digmârs Juliâns Rota Zigmârs\0"
    "Gatis Ivanda\0"
    "Aksels Alta Kaspars\0"
    "Dorisa Tatjana\0"
    "Franciska Smaida\0"
    "Reina Reinholds Reinis Renâts\0"
    "Aira Ârijs Âris Harijs\0"
    "Raitis Raits Roberta Roberts\0"
    "Felicita Fçlikss\0"
    "Lida Lidija\0"
    "Dravis Tenis\0"
    "Antis Antons\0"
    "Alnis Andulis\0"
    "Aïìirds Alìis Oïìerts Orests\0"
    "Agne Agnese Agnija\0"
    "Austris\0"
    "Grieta Strauta\0"
    "Eglons Kriðs Ksenija\0"
    "Sigurds Zigurds\0"
    "Agneta Agnis Ansis\0"
    "Ildze Ilze Izolde\0"
    "Kârlis Spodris\0"
    "Aivars Valçrijs\0"
    "Pârsla Tîna Valentîna\0"
    "Tekla Violeta"
};
const char MONTH_2[] PROGMEM = {
    "Brigita Indars Indra Indris\0"
    "Sonora Spîdola\0"
    "Aîda Ida Vida\0"
    "Daila Veronika\0"
    "Agate Selga Silga Sinilga\0"
    "Dace Dârta Dora\0"
    "Nelda Rièards Rihards\0"
    "Aldona\0"
    "Apolonija Simona\0"
    "Paula Paulîne\0"
    "Laima Laimdota\0"
    "Karlîna Lîna\0"
    "Malda Melita\0"
    "Valentîns\0"
    "Aloizs Alvils Olafs Olavs\0"
    "Dþuljeta Jûlija\0"
    "Donats Konstance\0"
    "Kintija Kora\0"
    "Zane Zuzanna\0"
    "Smuidra Smuidris Vitauts\0"
    "Ariadne Eleonora\0"
    "Adrians Ârija Rigonda\0"
    "Almants Haralds\0"
    "Diâna Dina Dins\0"
    "Alma Annemarija\0"
    "Aurçlija Evelîna Mçtra\0"
    "Andra Lîva Lîvija\0"
    "Justs Skaidra Skaidrîte"
};
const char MONTH_3[] PROGMEM = {
    "Ilgvars Ivars\0"
    "Laila Lavîze Luîze\0"
    "Marts Tâlavs Tâlis\0"
    "Alise Auce\0"
    "Aurora Austra\0"
    "Centis Gotfrîds Vents\0"
    "Ella Elmîra\0"
    "Dagmâra Marga Margita\0"
    "Çvalds\0"
    "Laimrota Liliâna Silvija\0"
    "Agita Konstantîns\0"
    "Aija Aiva Aivis\0"
    "Balvis Ernests\0"
    "Matilde Ulrika\0"
    "Amalda Amilda Imalda\0"
    "Guntars Guntis Guntris\0"
    "Gerda Gertrûde Ìertrûde\0"
    "Adelîna Ilona\0"
    "Jâzeps\0"
    "Irbe Made\0"
    "Benedikts Dzelme Una Unigunde\0"
    "Dziedra Tamâra\0"
    "Mirdza Þanete Þanna\0"
    "Izidors Kazimirs\0"
    "Mâra Marita Mârîte\0"
    "Eiþenija Þenija\0"
    "Gustavs Gusts Tâlrîts\0"
    "Ginta Gunda Gunta\0"
    "Agija Aldonis\0"
    "Igmârs Ilgmârs Nanija\0"
    "Atvars Gvido"
};
const char MONTH_4[] PROGMEM = {
    "Dagne Dagnis\0"
    "Imgarde Irmgarde\0"
    "Daira Dairis\0"
    "Ârvalda Ârvalds Herta Valda\0"
    "Aivija Vidaga Vija\0"
    "Dzinta Filips Vîlips Zinta\0"
    "Helmuts Zina Zinaîda\0"
    "Dana Dans Danute Edgars\0"
    "Valçrija Þubîte\0"
    "Anita Anitra Zîle\0"
    "Hermanis Vilmârs\0"
    "Ainis Jûlijs\0"
    "Egîls Nauris\0"
    "Gudrîte Strauja\0"
    "Aelita Gastons\0"
    "Alfs Bernadeta Mintauts\0"
    "Rûdis Rûdolfs Viviâna\0"
    "Jadviga Laura\0"
    "Fanija Vçsma\0"
    "Mirta Ziedîte\0"
    "Anastasija Marìers\0"
    "Armanda Armands\0"
    "Georgs Jurìis Juris\0"
    "Nameda Ritvaldis Visvaldis\0"
    "Bârbala Lîksma\0"
    "Alîna Rûsiòð Sandris\0"
    "Klementîne Raimonda Raina Tâle\0"
    "Gundega Terçze\0"
    "Laine Raimonds Vilnis\0"
    "Liâna Lilija"
};
const char MONTH_5[] PROGMEM = {
    "Ziedonis\0"
    "Sigmunds Zigismunds Zigmunds\0"
    "Gints Uvis\0"
    "Vijolîte Viola Vizbulîte\0"
    "Ìederts Ìirts\0"
    "Didzis Gaidis\0"
    "Henriete Henrijs Jete\0"
    "Staòislava Staòislavs Stefânija\0"
    "Einârs Ervîns Klâvs\0"
    "Maija Paija\0"
    "Karmena Manfreds Milda\0"
    "Ina Inâra Inârs Valija\0"
    "Ira Iraîda Irçna Irina\0"
    "Aivita Elfa Elvita Kriðjânis\0"
    "Airita Arita Sofija Taiga\0"
    "Edijs Edvîns\0"
    "Dailis Herberts Umberts\0"
    "Çriks Inese Inesis\0"
    "Lita Sibilla Teika\0"
    "Salvis Selva Venta\0"
    "Akvelîna Ernestîne Ingmârs\0"
    "Emîlija\0"
    "Leokâdija Leontîne Ligija Lonija\0"
    "Ilvija Marlçna Ziedone\0"
    "Anðlavs Junora\0"
    "Eduards Edvards Varis\0"
    "Dzidra Dzidris Gunita Loreta\0"
    "Vilhelms Vilis\0"
    "Maksis Raivis Raivo\0"
    "Lolita Vitolds\0"
    "Alîda Jûsma"
};
const char MONTH_6[] PROGMEM = {
    "Bernedîne Biruta Mairita\0"
    "Emma Lîba\0"
    "Ineta Inta Intra\0"
    "Elfrîda Sindija Sintija\0"
    "Igors Ingvars Margots\0"
    "Ardis Ingrîda\0"
    "Arnis Gaida\0"
    "Frîda Frîdis Mundra\0"
    "Gita Ligita\0"
    "Anatols Malva\0"
    "Ingus Mairis Vidvuds\0"
    "Ija Lenora Nora\0"
    "Ainârs Uva Zigfrîds\0"
    "Saiva Saivis Santis Sentis Tija\0"
    "Baòuta Vilija Vits Þermçna\0"
    "Justîne Juta\0"
    "Artis Artûrs\0"
    "Alberts Madis\0"
    "Nils Viktors\0"
    "Maira Rasa Rasma\0"
    "Egita Emîls Monvîds\0"
    "Laimdots Laimiòð Ludmila\0"
    "Lîga\0"
    "Jânis\0"
    "Maiga Milija\0"
    "Ausma Ausmis Inguna Inguns\0"
    "Malvîne Malvis\0"
    "Kitija Viestards Viesturs\0"
    "Paulis Pauls Pâvils Pçteris\0"
    "Mareks Tâlivaldis"
};
const char MONTH_7[] PROGMEM = {
    "Imants Ingars Intars Rimants\0"
    "Halina Ilvars Lauma\0"
    "Benita Everita Verita\0"
    "Sandis Uldis Ulvis\0"
    "Andþejs Andþs Edîte Esmeralda\0"
    "Anrijs Arkâdijs\0"
    "Alda Maruta\0"
    "Ada Adele Antra\0"
    "Asna Asne Zaiga\0"
    "Lija Olîvija\0"
    "Leonora Svens\0"
    "Indriíis Ints Namejs\0"
    "Margarita Margrieta\0"
    "Anvars Oskars Ritvars\0"
    "Egija Egmonts Egons Henrihs Henriks\0"
    "Estere Hermîne\0"
    "Aleksejs Aleksis\0"
    "Rozâlija Roze\0"
    "Digna Jautrîte Kamila\0"
    "Ramona Ritma\0"
    "Meldra Meldris Melisa\0"
    "Marija Marika Marina\0"
    "Magda Magdalçna Magone Mçrija\0"
    "Krista Kristiâna Kristiâns Kristîne\0"
    "Jçkabs Þaklîna\0"
    "Ance Anna Annija\0"
    "Dita Marta\0"
    "Cecîlija Cilda\0"
    "Edmunds Edþus Vidmants\0"
    "Renârs Valters\0"
    "Angelika Rûta Sigita"
};
const char MONTH_8[] PROGMEM = {
    "Albîna Albîns\0"
    "Normunds Stefans\0"
    "Augusts\0"
    "Româns Romualda Romualds\0"
    "Arvils Osvalds\0"
    "Aisma Askolds\0"
    "Alfrçds Fredis Madars\0"
    "Mudîte Vladislava Vladislavs\0"
    "Genoveva Madara\0"
    "Audris Brencis Inuta\0"
    "Liega Olga Zigita Zita\0"
    "Klâra Vizma\0"
    "Elvîra Velga\0"
    "Virma Zelma Zemgus\0"
    "Dzelde Zelda Zenta\0"
    "Astra Astrîda\0"
    "Oïegs Vineta\0"
    "Elena Ellena Helçna Liena Liene\0"
    "Imanta Melânija\0"
    "Bernhards Boriss\0"
    "Janîna Linda\0"
    "Everts Rudîte\0"
    "Ralfs Valgudis Vitâlijs\0"
    "Bçrtulis Boïeslavs\0"
    "Ivonna Ludis Ludvigs Patrîcija\0"
    "Broòislava Broòislavs Natâlija Tâlija\0"
    "Alens Jorens Þanis\0"
    "Auguste Guste\0"
    "Aiga Armîns Vismants\0"
    "Alvis Jolanta Samanta\0"
    "Aigars Vilma"
};
const char MONTH_9[] PROGMEM = {
    "Austrums Ilmârs Iluta\0"
    "Elîza Lizete Zete\0"
    "Bella Berta\0"
    "Dzintara Dzintars Dzintra\0"
    "Klaudija Persijs Vaida\0"
    "Magnuss Maigonis Mariuss\0"
    "Ermîns Regîna\0"
    "Ilga\0"
    "Bruno Telma\0"
    "Albertîne Jausma\0"
    "Signe Signija\0"
    "Erna Eva Evita\0"
    "Iza Izabella\0"
    "Sanda Sanija Sanita Santa\0"
    "Gunvaldis Gunvaris Sandra Sondra\0"
    "Asja Asnate Dâgs Dârgs\0"
    "Vaira Vairis Vera\0"
    "Alita Elita Liesma\0"
    "Muntis Verners\0"
    "Ginters Guntra Marianna\0"
    "Mariss Matîss Modris\0"
    "Maigurs Mârica Mâris\0"
    "Vanda Veneranda Venija\0"
    "Agris Agrita\0"
    "Rauls Rodrigo\0"
    "Gundars Knuts Kurts\0"
    "Âdolfs Ilgonis\0"
    "Lana Sergejs Svetlana\0"
    "Mihails Miíelis Miks Mikus\0"
    "Elma Elna Menarda"
};
const char MONTH_10[] PROGMEM = {
    "Lâsma Zanda Zandis\0"
    "Ilma Skaidris\0"
    "Elza Ilizana\0"
    "Francis Modra\0"
    "Amâlija\0"
    "Monika Zilga Zilgma\0"
    "Daumants Druvvaldis\0"
    "Aina Anete\0"
    "Elga Elgars Helga\0"
    "Arvîds Arvis Druvis\0"
    "Monta Silva Tince\0"
    "Kira Valfrîds\0"
    "Irma Mirga\0"
    "Minna Vilhelmîne\0"
    "Eda Hedviga Helvijs\0"
    "Daiga Dinija\0"
    "Gaits Karîna\0"
    "Erlends Rolanda Rolands Ronalds\0"
    "Drosma Drosmis Elîna\0"
    "Leonîda Leonîds\0"
    "Severîns Urzula\0"
    "Irîda Îrisa\0"
    "Daina Dainida Dainis\0"
    "Modrîte Mudrîte Renâte\0"
    "Beâte Beatrise\0"
    "Amanda Amanta Kaiva\0"
    "Irita Ita Lilita\0"
    "Antoòina Òina Ninona Oksana\0"
    "Elva Elvijs Elvis Laimis Laimonis\0"
    "Nadîna Ulla\0"
    "Rinalda Rinalds Valts"
};
const char MONTH_11[] PROGMEM = {
    "Ikars\0"
    "Dzîle Viva Vivita\0"
    "Dagnija Çrika\0"
    "Atis Oto Otomârs\0"
    "Lote Ðarlote\0"
    "Leo Leonards Leons Linards\0"
    "Helma Lotârs\0"
    "Agra Aleksandra\0"
    "Teodors\0"
    "Mârcis Markuss Mârtiòð\0"
    "Nellija Ojârs Rainers\0"
    "Kaija Kornçlija\0"
    "Eiþens Jevgçòija Jevgçòijs\0"
    "Fricis Vikentijs\0"
    "Leopolds Unda Undîne\0"
    "Banga Glorija\0"
    "Hugo Uga Uìis\0"
    "Aleksandrs Doloresa\0"
    "Betija Elizabete Liza Lîze\0"
    "Anda Andîna\0"
    "Andis Zeltîte\0"
    "Aldis Aldris Alfons\0"
    "Zigfrîda Zigrîda Zigrîds\0"
    "Velda Velta\0"
    "Kadrija Kate Katrîna Trîne\0"
    "Konrâds Sebastians Sebastijans\0"
    "Lauris Norberts\0"
    "Olita Rita Vita\0"
    "Ignats Virgînija\0"
    "Andrejs Andrievs Andris"
};
const char MONTH_12[] PROGMEM = {
    "Arnolds Emanuels\0"
    "Meta Sniedze\0"
    "Evija Jogita Raita\0"
    "Baiba Barba Barbara\0"
    "Klaudijs Sabîne Sarma\0"
    "Niklâvs Nikolajs Niks\0"
    "Anta Antonija Dzirkstîte\0"
    "Gunârs Gunis Vladimirs\0"
    "Sarmîte Tabita\0"
    "Guna Judîte\0"
    "Valdemârs Valdis Voldemârs\0"
    "Iveta Otîlija\0"
    "Lûcija Veldze\0"
    "Auseklis Gaisma\0"
    "Hanna Jana Johanna\0"
    "Alvîne\0"
    "Hilda Teiksma\0"
    "Klinta Kristaps Kristofers Krists\0"
    "Lelde Sarmis\0"
    "Arta Minjona\0"
    "Saulcerîte Tomass Toms\0"
    "Saulvedis\0"
    "Balva Viktorija\0"
    "Âdams Ieva\0"
    "Larisa Stella\0"
    "Dainuvîte Gija Megija\0"
    "Elmârs Inita\0"
    "Inga Ingeborga Irvita Ivita\0"
    "Ilgona Solveiga\0"
    "Daniela Dâniels Dâvids Dâvis\0"
    "Kalvis Silvestrs Silvis"
};

enum { MAX_NAMES_LEN = 38 };

#endif // VD_NAMES
