# Sources are all project source files, excluding MansOS files
SOURCES = main.c

# Module is the name of the main module buit by this makefile
APPMOD = App

# --------------------------------------------------------------------
# Set the key variables
PROJDIR = $(CURDIR)
ifndef MOSROOT
  MOSROOT = $(PROJDIR)/../../../..
endif

# Include the main makefile
include ${MOSROOT}/mos/make/Makefile
