# This file is automatically generated by sensorlist.py script

from wmp import *

class Component(object):
    def __init__(self, name, varname, code):
        self.name = name
        self.varname = varname
        self.code = code

class Sensor(Component):
    def __init__(self, name, varname, code):
        super(Sensor, self).__init__(name, varname, code)
        self.period = 0

class Output(Component):
    def __init__(self, name, varname, code):
        super(Output, self).__init__(name, varname, code)
        self.selected = False

light = Sensor("Light", "light", WMP_SENSOR_LIGHT)
humidity = Sensor("Humidity", "humidity", WMP_SENSOR_HUMIDITY)
battery = Sensor("Battery (internal voltage)", "battery", WMP_SENSOR_BATTERY)
ADC0 = Sensor("ADC channel 0", "ADC0", WMP_SENSOR_ADC0)
ADC1 = Sensor("ADC channel 1", "ADC1", WMP_SENSOR_ADC1)
ADC2 = Sensor("ADC channel 2", "ADC2", WMP_SENSOR_ADC2)
ADC3 = Sensor("ADC channel 3", "ADC3", WMP_SENSOR_ADC3)
ADC4 = Sensor("ADC channel 4", "ADC4", WMP_SENSOR_ADC4)
ADC5 = Sensor("ADC channel 5", "ADC5", WMP_SENSOR_ADC5)
ADC6 = Sensor("ADC channel 6", "ADC6", WMP_SENSOR_ADC6)
ADC7 = Sensor("ADC channel 7", "ADC7", WMP_SENSOR_ADC7)

serial = Output("Serial port", "serial", WMP_OUTPUT_SERIAL)

sensors = [light, humidity, battery, ADC0, ADC1, ADC2, ADC3, ADC4, ADC5, ADC6, ADC7]
outputs = [serial]
